Make some improvements.

diff --git a/video-convert b/video-convert
--- a/video-convert
+++ b/video-convert
@@ -1,55 +1,72 @@
 #!/bin/bash
-INPUT_FILE=$1
-RESOLUTION=$2
-FRAMERATE=$3
 
-CRF=23
-PRESET=veryfast
+# Define input file and parameters
+FRAMERATE=${3:-"30"}     # Set default framerate to 30 if not provided
 
+help() {
+	cat << EOF
+Usage: rpm-crossbuild -i <directory> -o <directory>
+
+Options:
+    -i <file>             Input file (mandatory)
+    -f <framerate>        Output frame rate (23, 30 or 40) (mandatory)
+    -r <resolution>       Ourput resolution (480, 720 or 1080) (mandatory)
+EOF
+	exit 1
+}
+
+# Check command line options
+while getopts "r:f:i:h" flag; do
+	case $flag in
+		r) RESOLUTION=$OPTARG ;;
+		i) INPUT_FILE=$OPTARG ;;
+		f) FRAMERATE=$OPTARG ;;
+		h) help ;;
+		*)
+			echo 'Unknown option.'
+			exit 1
+			;;
+	esac
+done
+
+# Validate input parameters
 case "$RESOLUTION" in
-	"1080")
-		echo "1080 ok"
-		;;
-	"720")
-		echo "720 ok"
-		;;
-	"480")
-		echo "480 ok"
-		;;
+	"1080" |  "720" | "480") ;;
 	*)
-		echo "invalid resolution (1080/720/480 only)"
-		exit
+		echo     "Invalid resolution (1080/720/480 only)"
+		exit     1
 		;;
 esac
 
 case "$FRAMERATE" in
-	"60") ;;
-	"30") ;;
-	"25") ;;
+	"60" |  "30" | "25") ;;
 	*)
-		echo "invalid framerate (30/60/25 only)"
-		exit
+		echo     "Invalid framerate (30/60/25 only)"
+		exit     1
 		;;
 esac
 
+# Extract file extension and create output filename
 EXTENSION="${INPUT_FILE##*.}"
-OUTPUT_FILE=$(basename "$INPUT_FILE" \
-	| sed "s/\.$EXTENSION/ "$RESOLUTION"p$FRAMERATE.$EXTENSION/")
+OUTPUT_FILE=$(basename "$INPUT_FILE" | sed "s/\.$EXTENSION/ ${RESOLUTION}p${FRAMERATE}.${EXTENSION}/")
 
-if [[ -f $INPUT_FILE && ! -f "$OUTPUT_FILE"   ]]; then
-	if [[ $RESOLUTION == "480" ]]; then
+# Convert video using ffmpeg
+if [ -f "$INPUT_FILE" ] && ! [ -f "$OUTPUT_FILE" ]; then
+	if  [ "$RESOLUTION" = "480" ]; then
 		ffmpeg -i "$INPUT_FILE" -vf scale=854:480 -c:v libx264 -r $FRAMERATE \
-			-crf $CRF -preset $PRESET -c:a copy "$OUTPUT_FILE"
+			-crf        23 -preset veryfast -c:a copy "$OUTPUT_FILE"
 	else
 		ffmpeg -i "$INPUT_FILE" -vf scale=-1:$RESOLUTION -c:v libx264 -r \
-			$FRAMERATE -crf $CRF -preset $PRESET -c:a copy "$OUTPUT_FILE"
+			$FRAMERATE        -crf 23 -preset veryfast -c:a copy "$OUTPUT_FILE"
 	fi
+
+	# Check if conversion was successful and notify user
 	if [ $? -eq 0 ]; then
-		notify-send "Video erfolgreich konvertiert: $OUTPUT_FILE"
+		notify-send     "Video successfully converted: $OUTPUT_FILE"
 	else
-		notify-send "Video konnte nicht konveritert werden"
+		notify-send     "Failed to convert video"
 		rm "$OUTPUT_FILE"
 	fi
 else
-	notify-send "Fehler, wurde das Video schon konvertiert?"
+	notify-send  "Error: Video already converted?"
 fi
