Update scripts.

diff --git a/video-convert b/video-convert
--- a/video-convert
+++ b/video-convert
@@ -31,18 +31,18 @@ done
 
 # Validate input parameters
 case "$RESOLUTION" in
-	"1080" |  "720" | "480") ;;
+	"1080" | "720" | "480") ;;
 	*)
-		echo     "Invalid resolution (1080/720/480 only)"
-		exit     1
+		echo   "Invalid resolution (1080/720/480 only)"
+		exit   1
 		;;
 esac
 
 case "$FRAMERATE" in
-	"60" |  "30" | "25") ;;
+	"60" | "30" | "25") ;;
 	*)
-		echo     "Invalid framerate (30/60/25 only)"
-		exit     1
+		echo   "Invalid framerate (30/60/25 only)"
+		exit   1
 		;;
 esac
 
@@ -52,21 +52,21 @@ OUTPUT_FILE=$(basename "$INPUT_FILE" | sed "s/\.$EXTENSION/ ${RESOLUTION}p${FRAM
 
 # Convert video using ffmpeg
 if [ -f "$INPUT_FILE" ] && ! [ -f "$OUTPUT_FILE" ]; then
-	if  [ "$RESOLUTION" = "480" ]; then
+	if [ "$RESOLUTION" = "480" ]; then
 		ffmpeg -i "$INPUT_FILE" -vf scale=854:480 -c:v libx264 -r $FRAMERATE \
-			-crf        23 -preset veryfast -c:a copy "$OUTPUT_FILE"
+			-crf      23 -preset veryfast -c:a copy "$OUTPUT_FILE"
 	else
 		ffmpeg -i "$INPUT_FILE" -vf scale=-1:$RESOLUTION -c:v libx264 -r \
-			$FRAMERATE        -crf 23 -preset veryfast -c:a copy "$OUTPUT_FILE"
+			$FRAMERATE      -crf 23 -preset veryfast -c:a copy "$OUTPUT_FILE"
 	fi
 
 	# Check if conversion was successful and notify user
 	if [ $? -eq 0 ]; then
-		notify-send     "Video successfully converted: $OUTPUT_FILE"
+		notify-send   "Video successfully converted: $OUTPUT_FILE"
 	else
-		notify-send     "Failed to convert video"
+		notify-send   "Failed to convert video"
 		rm "$OUTPUT_FILE"
 	fi
 else
-	notify-send  "Error: Video already converted?"
+	notify-send "Error: Video already converted?"
 fi
